### ISSUE TITLE
Do you have same extension for magento 2 ?

### ISSUE THREAD

**Issue by sumeetmagento** [MaWoScha/Unicode_FileUploader#11]
Do you have the same extension for Magento 2?
because my website migrate 1 to 2 so need to the same extension for mgento2

**Comment by MaWoScha** [comment]
obvious: no

**Comment by Eddcapone** [comment]
Are there plans to develope the extension for M2

**Comment by MaWoScha** [comment]
Are there any plans to pay me?

**Comment by Eddcapone** [comment]
My company would pay you, but you seem to be unprofessional. So obviously: no

**Comment by MaWoScha** [comment]
so you think your are doing a professional discussion? *lol*

**Comment by Eddcapone** [comment]
No, because you are not professional. Bye

**Comment by MaWoScha** [comment]
I never claimed to be professional, idiot. But you want stuff free from me.
*fuck you*

**Comment by Eddcapone** [comment]
I never said that I will stuff free from you, I said that my company would have payed you. Learn to read you analphabethic little shit.
