### ISSUE TITLE
modman incomplete

### ISSUE THREAD

**Issue by Elfen-Service** [MaWoScha/Unicode_FileUploader#5]
There are missing folders and files ...

Not ideal but better:
`lib/Varien/Data/Form/Element/Fileuploader.php lib/Varien/Data/Form/Element/Fileuploader.php
js/fileuploader/filepop.js js/fileuploader/filepop.js
app/etc/modules/Uni_Common.xml app/etc/modules/Uni_Common.xml
app/etc/modules/Uni_Fileuploader.xml app/etc/modules/Uni_Fileuploader.xml
app/design/adminhtml/default/default/template/fileuploader/ app/design/adminhtml/default/default/template/fileuploader/
app/design/adminhtml/default/default/layout/fileuploader.xml app/design/adminhtml/default/default/layout/fileuploader.xml
app/design/frontend/base/default/template/fileuploader/ app/design/frontend/base/default/template/fileuploader/
app/design/frontend/base/default/layout/fileuploader.xml app/design/frontend/base/default/layout/fileuploader.xml
app/code/community/Uni/Common/ app/code/community/Uni/Common/
app/code/community/Uni/Fileuploader/ app/code/community/Uni/Fileuploader/
app/locale/fr_FR/Uni_Fileuploader.csv app/locale/fr_FR/Uni_Fileuploader.csv
app/locale/pt_PT/Uni_Fileuploader.csv app/locale/pt_PT/Uni_Fileuploader.csv
app/locale/es_ES/Uni_Fileuploader.csv app/locale/es_ES/Uni_Fileuploader.csv
app/locale/de_DE/Uni_Fileuploader.csv app/locale/de_DE/Uni_Fileuploader.csv
app/locale/en_US/Uni_Fileuploader.csv app/locale/en_US/Uni_Fileuploader.csv
media/custom/upload/icons/* media/custom/upload/icons/
media/custom/upload/player/* media/custom/upload/player/`

**Comment by MaWoScha** [comment]
done!
